//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorAnalysis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public string Text { get; set; }
        public double AverageSentenceWordCount { get; set; }
        public double PunctoationToWordRatio { get; set; }
        public double NounToWordRatio { get; set; }
        public double VerbToWordRatio { get; set; }
        public double AdjectiveToWordRatio { get; set; }
        public double AdverbToWordRatio { get; set; }
        public int AuthorID { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
