//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorAnalysis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamedEntity
    {
        public int BookID { get; set; }
        public string NamedEntity1 { get; set; }
        public int NumberOfOccurences { get; set; }
        public int NamedEntityID { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
